[package]
name = "mqttui"
version = "0.11.1"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
authors = ["EdJoPaTo <mqttui-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
crossterm = "0.19"
json = "0.12"
rand = "0.8"
rumqttc = "0.5"
tui-tree-widget = "0.4"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.tui]
version = "0.14"
default-features = false
features = ["crossterm"]
