[package]
name = "mqtt"
version = "0.1.0"
description = "Small Command Line Utility to quickly publish or subscribe something to a given mqtt topic"
authors = ["EdJoPaTo <quick-mqtt-cli-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rumqttc = "0.1"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]
