[package]
name = "mqtt-cli"
version = "0.1.0"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
authors = ["EdJoPaTo <mqtt-cli-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="mqtt"
path="src/main.rs"

[dependencies]
chrono = "0.4"
rand = "0.7"
rumqttc = "0.1"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]
