[package]
name = "mqttui"
version = "0.8.0"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
authors = ["EdJoPaTo <mqttui-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
crossterm = "0.18"
json = "0.12"
rand = "0.7"
rumqttc = "0.2"
tui-tree-widget = "0.1"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]

[dependencies.tui]
version = "0.12"
default-features = false
features = ["crossterm"]
